### ISSUE TITLE
saucelabs-espresso-app-automate@0 (exit code: 126) 

### ISSUE THREAD

**Issue by rjravijoshi111** [moatazeldebsy/bitrise-step-saucelabs-espresso-app-automate#3]
Hello

I am getting this error with bitrise

![Screenshot 2021-09-29 at 12 50 00 AM](https://user-images.githubusercontent.com/31402163/135152104-c5f2e355-4d5c-47c7-9e33-b100eeeb40f8.png)

**Comment by moatazeldebsy** [comment]
Hello, can you add the full error message I can see only "cannot...."

**Comment by sergavt** [comment]
/step_src/step.sh: line 11: ./sauce-runner-virtual-0.1.1-linux/bin/sauce-runner-virtual: cannot execute binary file

**Comment by moatazeldebsy** [comment]
Hi @sergavt this step will be deprecated soon with a new step because Sauce Labs now is using a different CLI tool.

**Comment by sergavt** [comment]
@moatazeldebsy we are a little behind our automation plans because of this issue.  How soon do you think we can get the upgraded version from you?  Also do we need to use saucectl in order to make your solution work for Bitrise-SauceLabs integration?  Is this fix going to work if we use just appium + XCUITest?

**Comment by sergavt** [comment]
We resolved issue with the Script step in Bitrise.   
============================================
#!/bin/bash

echo "Installing saucectl globally"
npm install -g saucectl

echo "Configure user name and access key"
saucectl configure -u $SAUCELABS_USERNAME -a $SAUCELABS_ACCESS_KEY

echo "Upload .apk file to storage at SauceLabs"
saucectl storage upload <apk-path> --force —out text

**Comment by moatazeldebsy** [comment]
@sergavt Yes, this is what I was planning to suggest to you. You can use `saucectl`, and here is a detailed blog post on how to use it [https://bitrise.io/blog/post/continuous-testing-for-mobile-apps-at-scale-with-sauce-labs-and-bitrise](https://bitrise.io/blog/post/continuous-testing-for-mobile-apps-at-scale-with-sauce-labs-and-bitrise)
